### ISSUE TITLE
Incorrect main file in package.json

### ISSUE THREAD

**Issue by jacobkossman** [nooooooom/merge-dirs#1]
```
Error: Cannot find module '/Users/jacob/XXXX/node_modules/@nooooooom/merge-dirs/dist/index.ts'. Please verify that the package.json has a valid "main" entry
```

Changing package.json to list 'dist/index.js' as the main file not 'dist/index.ts' fixes this.

Thanks!

**Comment by nooooooom** [comment]
Thanks for your advice!
This is the first issue I've received; I'll try to make it better!

**Comment by nooooooom** [comment]
My original goal was to merge the two folders deep, but I should have noticed some things regarding usage, and today I decided to spend time rethinking and refactoring it.
