### ISSUE TITLE
Add ignore files / folders option?

### ISSUE THREAD

**Issue by jacobkossman** [nooooooom/merge-dirs#2]
Wondering if there's a way to specify an ignore list of single files or folders?

For example, I'm merging `dir A` and `dir B` into a completely new folder `dir C`. `dir A` has a node_module folder in it along with some other dev files I don't want to end up in `dir C`. Ideally, I would be able to say: "ignore node_modules and package.json" etc. This way my final destination folder is clean.

Thanks!

**Comment by nooooooom** [comment]
Thanks for your advice!
I have this idea, and I also want to be able to do some restrictions on the path based on `fast-glob`.

**Comment by nooooooom** [comment]
I refactored the use of `merge-dirs` in `v2.0.0`.

If you want to merge `dir A` and `dir B` into `dir C`,  you can use
```ts
mergeDirs({
  targets: [
    {
      dest: 'dir C',
      src: ['dir A/*', 'dir B/*'],
      // if you want ignore `node_modules`
      ignore: ['**/node_modules']
    }
  ]
})
```

If you want to merge specific files into `dir C`,  you can use
```ts
mergeDirs({
  targets: [
    {
      dest: 'dir C',
      src: 'dir A/**/*.ts',
      // set `flatten` to `true` and we will flatten merge all specific files
      flatten: true
    }
  ]
})
```

If you want to merge specific files into `dir C` and need to keep the file structure, you can use
```ts
mergeDirs({
  targets: [
    {
      dest: 'dir C',
      // we can ignore this hierarchy by setting `dir A` as `root`
      root: 'dir A',
      src: '**/*.ts'
    }
  ]
})
```

**Comment by jacobkossman** [comment]
thank you for the update however maybe i'm misunderstanding how the refactor works. i'm attempting to merge two folders `base` and `instance` into a single folder `build`. This is my code:

```
function runMerge(){
	mergeDirs({
		targets: [
			{
				dest: '../build',
				src: [
					'../base',
					'../instance'
				],
				ignore: ['../**/node_modules']
			}
		]
	});
}

runMerge();

```

the result is:

build:
-- instance
-- base

instead of actually merging them. do i need to add a second object in the targets array?

**Comment by nooooooom** [comment]
> thank you for the update however maybe i'm misunderstanding how the refactor works. i'm attempting to merge two folders `base` and `instance` into a single folder `build`. This is my code:
> 
> ```
> function runMerge(){
> 	mergeDirs({
> 		targets: [
> 			{
> 				dest: '../build',
> 				src: [
> 					'../base',
> 					'../instance'
> 				],
> 				ignore: ['../**/node_modules']
> 			}
> 		]
> 	});
> }
> 
> runMerge();
> ```
> 
> the result is:
> 
> build: -- instance -- base
> 
> instead of actually merging them. do i need to add a second object in the targets array?

You can configure by:

```js
{
  dest: '../build',
  src: [
	'../base/*',
	'../instance/*'
  ],
  flatten: true,
  ignore: ['../**/node_modules']
}
```
I'll update the docs later to introduce the merge mechanism after the refactoring.

**Comment by jacobkossman** [comment]
@nooooooom awesome. the 'flatten' was the missing piece there, i thought it was to just remove all folders and just have files. i've got it working now, appreciate the quick response!

**Comment by nooooooom** [comment]
> @nooooooom awesome. the 'flatten' was the missing piece there, i thought it was to just remove all folders and just have files. i've got it working now, appreciate the quick response!

Glad to be able to help you with your work. To support the `fast-glob` parsing mode, the logic after refactoring is quite different from before, and I am trying to make it support more scenarios.
